<a href="https://colab.research.google.com/github/Prakrut/NeuralNets/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Artificial Neural Network Using Tesorflow

Import Libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [4]:
tf.__version__


'2.3.0'

# Data Preprocessing

In [11]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:,-1].values

In [13]:
print(X.shape)
X

(10000, 10)


array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

Encoding categorical data

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [14]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

Gender Column (Only using LabelEncoding for Male/Female)

In [20]:
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [29]:
dataset.head(6)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0
5          6    15574012       Chu  ...               0       149756.71      1

[6 rows x 14 columns]

Onehotencoding for Geography

In [31]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough', verbose=True)
X = np.array(ct.fit_transform(X))


[ColumnTransformer] ....... (1 of 2) Processing encoder, total=   0.0s
[ColumnTransformer] ..... (2 of 2) Processing remainder, total=   0.0s


In [32]:
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

Split Data into Train and Test

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

Feature Scaling

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [36]:
print(X_train)

[[ 0.99750312 -0.58042949 -0.57234647 ... -1.5547807  -1.02429504
  -1.50614218]
 [ 0.99750312 -0.58042949 -0.57234647 ...  0.64317752 -1.02429504
  -0.25873586]
 [-1.00250313  1.72286214 -0.57234647 ... -1.5547807   0.97628121
  -0.1770722 ]
 ...
 [-1.00250313  1.72286214 -0.57234647 ...  0.64317752 -1.02429504
   1.31024568]
 [ 0.99750312 -0.58042949 -0.57234647 ...  0.64317752  0.97628121
  -1.62403582]
 [ 0.99750312 -0.58042949 -0.57234647 ...  0.64317752 -1.02429504
   0.57382344]]


# Build ANN using TF

Initialize the ANN

In [37]:
ann = tf.keras.models.Sequential()

In [38]:
ann.add(tf.keras.layers.Dense(6, activation='relu'))

In [39]:
ann.add(tf.keras.layers.Dense(1,activation='sigmoid'))

# Train ANN

Compile ANN with Adam optimizer using binary cross entropy for loss function and accuracy as metrics

In [40]:
ann.compile(optimizer='adam',
            loss='binary_crossentropy',
            metrics=['accuracy'])

Training the model

In [41]:
ann.fit(x = X_train,
        y = y_train,
        batch_size = 32,
        epochs = 100,
        verbose = 2)

Epoch 1/100
250/250 - 0s - loss: 0.6445 - accuracy: 0.6660
Epoch 2/100
250/250 - 0s - loss: 0.4830 - accuracy: 0.8009
Epoch 3/100
250/250 - 0s - loss: 0.4482 - accuracy: 0.8101
Epoch 4/100
250/250 - 0s - loss: 0.4334 - accuracy: 0.8156
Epoch 5/100
250/250 - 0s - loss: 0.4245 - accuracy: 0.8214
Epoch 6/100
250/250 - 0s - loss: 0.4182 - accuracy: 0.8242
Epoch 7/100
250/250 - 0s - loss: 0.4126 - accuracy: 0.8271
Epoch 8/100
250/250 - 0s - loss: 0.4065 - accuracy: 0.8305
Epoch 9/100
250/250 - 0s - loss: 0.4002 - accuracy: 0.8340
Epoch 10/100
250/250 - 0s - loss: 0.3934 - accuracy: 0.8391
Epoch 11/100
250/250 - 0s - loss: 0.3862 - accuracy: 0.8407
Epoch 12/100
250/250 - 0s - loss: 0.3786 - accuracy: 0.8459
Epoch 13/100
250/250 - 0s - loss: 0.3724 - accuracy: 0.8476
Epoch 14/100
250/250 - 0s - loss: 0.3669 - accuracy: 0.8508
Epoch 15/100
250/250 - 0s - loss: 0.3620 - accuracy: 0.8519
Epoch 16/100
250/250 - 0s - loss: 0.3585 - accuracy: 0.8545
Epoch 17/100
250/250 - 0s - loss: 0.3555 - accura

In [43]:
dataset.loc[dataset.Geography=='France'].head(1)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1

[1 rows x 14 columns]

In [44]:
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [47]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

[[False]]


Predicting Accuracy

In [57]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(y_pred)

[[ True]
 [False]
 [False]
 ...
 [ True]
 [False]
 [False]]


In [58]:
np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)

array([[1, 1],
       [0, 0],
       [0, 0],
       ...,
       [1, 0],
       [0, 0],
       [0, 0]])

In [59]:
from sklearn.metrics import confusion_matrix, accuracy_score


In [60]:
cm = confusion_matrix(y_test, y_pred)

In [61]:
cm

array([[1536,   57],
       [ 199,  208]])

In [62]:
accuracy_score(y_test, y_pred)

0.872